services:
  - type: web
    name: noemi-1-aninho
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    buildCommand: null
    pullRequestPreviewsEnabled: false
